// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 27 Nov 2022 10:05:52 PST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package xlib

/*
#cgo pkg-config: x11
#include "X11/Xlib.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"fmt"
	"runtime"
	"sync"
	"unsafe"
)

// Ref returns a reference to C object as it is.
func (x *Display) Ref() *C.Display {
	if x == nil {
		return nil
	}
	return (*C.Display)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *Display) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewDisplayRef converts the C object reference into a raw struct reference without wrapping.
func NewDisplayRef(ref unsafe.Pointer) *Display {
	return (*Display)(ref)
}

// NewDisplay allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewDisplay() *Display {
	return (*Display)(allocDisplayMemory(1))
}

// allocDisplayMemory allocates memory for type C.Display in C.
// The caller is responsible for freeing the this memory via C.free.
func allocDisplayMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfDisplayValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfDisplayValue = unsafe.Sizeof([1]C.Display{})

// cgoAllocMap stores pointers to C allocated memory for future reference.
type cgoAllocMap struct {
	mux sync.RWMutex
	m   map[unsafe.Pointer]struct{}
}

var cgoAllocsUnknown = new(cgoAllocMap)

func (a *cgoAllocMap) Add(ptr unsafe.Pointer) {
	a.mux.Lock()
	if a.m == nil {
		a.m = make(map[unsafe.Pointer]struct{})
	}
	a.m[ptr] = struct{}{}
	a.mux.Unlock()
}

func (a *cgoAllocMap) IsEmpty() bool {
	a.mux.RLock()
	isEmpty := len(a.m) == 0
	a.mux.RUnlock()
	return isEmpty
}

func (a *cgoAllocMap) Borrow(b *cgoAllocMap) {
	if b == nil || b.IsEmpty() {
		return
	}
	b.mux.Lock()
	a.mux.Lock()
	for ptr := range b.m {
		if a.m == nil {
			a.m = make(map[unsafe.Pointer]struct{})
		}
		a.m[ptr] = struct{}{}
		delete(b.m, ptr)
	}
	a.mux.Unlock()
	b.mux.Unlock()
}

func (a *cgoAllocMap) Free() {
	a.mux.Lock()
	for ptr := range a.m {
		C.free(ptr)
		delete(a.m, ptr)
	}
	a.mux.Unlock()
}

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *Display) PassRef() *C.Display {
	if x == nil {
		x = (*Display)(allocDisplayMemory(1))
	}
	return (*C.Display)(unsafe.Pointer(x))
}

type sliceHeader struct {
	Data unsafe.Pointer
	Len  int
	Cap  int
}

// copyPDisplayBytes copies the data from Go slice as *C.Display.
func copyPDisplayBytes(slice *sliceHeader) (*C.Display, *cgoAllocMap) {
	allocs := new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	mem0 := unsafe.Pointer(C.CBytes(*(*[]byte)(unsafe.Pointer(&sliceHeader{
		Data: slice.Data,
		Len:  int(sizeOfDisplayValue) * slice.Len,
		Cap:  int(sizeOfDisplayValue) * slice.Len,
	}))))
	allocs.Add(mem0)

	return (*C.Display)(mem0), allocs
}

// copyPXEventBytes copies the data from Go slice as *C.XEvent.
func copyPXEventBytes(slice *sliceHeader) (*C.XEvent, *cgoAllocMap) {
	allocs := new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	mem0 := unsafe.Pointer(C.CBytes(*(*[]byte)(unsafe.Pointer(&sliceHeader{
		Data: slice.Data,
		Len:  int(sizeOfXEventValue) * slice.Len,
		Cap:  int(sizeOfXEventValue) * slice.Len,
	}))))
	allocs.Add(mem0)

	return (*C.XEvent)(mem0), allocs
}

// allocXEventMemory allocates memory for type C.XEvent in C.
// The caller is responsible for freeing the this memory via C.free.
func allocXEventMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfXEventValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfXEventValue = unsafe.Sizeof([1]C.XEvent{})
