// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 27 Nov 2022 10:05:52 PST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "X11/Xlib.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

