// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 27 Nov 2022 10:14:54 PST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package xlib provides X11 bindings
*/
package xlib
