// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 27 Nov 2022 10:14:54 PST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package xlib

/*
#cgo pkg-config: x11
#include "X11/Xlib.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// Display as declared in X11/Xlib.h:487
type Display C.Display

// XEvent as declared in X11/Xlib.h:1009
const sizeofXEvent = unsafe.Sizeof(C.XEvent{})

type XEvent [sizeofXEvent]byte
